spring.application.name=StayFinder

# Perfil activo: Esto le dice a Spring que use el archivo de arriba
spring.profiles.active=prod

# Configuración común JPA
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false