# 1. Base de Datos (Usa las variables de tu .env)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Puerto del servidor
server.port=${SERVER_PORT:8080}

# 4. JWT Keys
jwt.key=${JWT_SECRET}
jwt.tokenExpiration=${JWT_EXPIRATION}

# 5. CONFIGURACIÓN DE CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=stayfinder0@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# 6. GOOGLE OAUTH (Usando variables del .env)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email